config/routes.rb
Rails.application.routes.draw do
  # Home with randomizer
  root 'home#index'

  # Only index and show to prevent unwanted changes
  resources :cards, only: [:index, :show]
end

app/models/card.rb
class Card < ActiveRecord::Base
  after_commit :print_card

  validates :topic, :definition, presence: true

  private

  def print_card
    puts self.topic
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  def index
    @cards = Card.all.order("topic ASC").group_by{|c| c.topic[0]}
  end

  # GET /cards/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params[:card]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    offset = rand(Card.count)
    @random_flashcard = Card.offset(offset).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def parse_markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true, :line_numbers => :table)
    markdown.render(text)
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :topic, placeholder: 'Topic' %>
  </div>
  <div class="field">
    <%= f.text_area :definition, placeholder: 'Definition' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'button' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h2>Alphabetical</h2>
<% @cards.each do |alpha, cards| -%>
  <h3><%= alpha %></h3>
  <ul class="index">
    <% cards.each do |card| -%>
    <li><%= link_to card.topic, card %></li>
    <% end -%>
  </ul>
<% end -%>
</ul>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<h2 id="topic"><%= @card.topic %></h2>

<div class="links">
  <%= link_to 'Show', '#', id: 'show-button', class: 'button' %>
  <%= link_to 'Hide', '#', id: 'hide-button', class: 'button' %>
</div>

<div id="definition">
  <%= parse_markdown(@card.definition).html_safe %>
</div>

app/views/home/index.html.erb
<h2 id="topic"><%= @random_flashcard.topic %></h2>

<div class="links">
  <%= link_to 'Show', '#', id: 'show-button', class: 'button' %>
  <%= link_to 'Hide', '#', id: 'hide-button', class: 'button' %>
  <%= link_to 'Refresh', '#', id: 'refresh-button', class: 'button' %>
</div>

<div id="definition">
  <%= parse_markdown(@random_flashcard.definition).html_safe %>
</div>

app/views/layouts/_favicon.html.erb
<%= favicon_link_tag 'favicons/apple-icon-57x57.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '57x57' %>
<%= favicon_link_tag 'favicons/apple-icon-60x60.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '60x60' %>
<%= favicon_link_tag 'favicons/apple-icon-72x72.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '72x72' %>
<%= favicon_link_tag 'favicons/apple-icon-76x76.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
<%= favicon_link_tag 'favicons/apple-icon-114x114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114' %>
<%= favicon_link_tag 'favicons/apple-icon-120x120.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
<%= favicon_link_tag 'favicons/apple-icon-144x144.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '144x144' %>
<%= favicon_link_tag 'favicons/apple-icon-152x152.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152' %>
<%= favicon_link_tag 'favicons/apple-icon-180x180.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180' %>
<%= favicon_link_tag 'favicons/favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>
<%= favicon_link_tag 'favicons/android-chrome-192x192.png', rel: 'icon', type: 'image/png', sizes: '192x192' %>
<%= favicon_link_tag 'favicons/favicon-96x96.png', rel: 'icon', type: 'image/png', sizes: '96x96' %>
<%= favicon_link_tag 'favicons/favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
<%= favicon_link_tag 'favicons/manifest.json', rel: 'manifest' %>
<%= favicon_link_tag 'favicons/safari-pinned-tab.svg', rel: 'mask-icon', color: '#5bbad5' %>
<%= favicon_link_tag 'favicons/', rel: '', type: 'image/png', sizes: '' %>
<%= favicon_link_tag 'favicons/', rel: '', type: 'image/png', sizes: '' %>
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/assets/favicons/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flash</title>
  <%= render partial: 'layouts/favicon' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <header>
      <%= link_to image_tag("logo.png", size: "30x30", class: "logo"), root_path %>
      <nav>
        <%= link_to "#{fa_icon "sort-alpha-asc"}".html_safe, cards_path %>
        <%= fa_icon "tag" %>
      </nav>
    </header>
    <%= yield %>
  </div>
</body>
</html>